{
 "title": "Validator Network Dashboard (Prometheus)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_num_txs", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Number of Validators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_validators", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Number of Byzantine Validators",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Receive Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_receive_bytes_total",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Total Power of Validators",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Number of Rounds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "cometbft_consensus_rounds", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Block Interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Total Power of Byzantine Validators",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators_power",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Validator Set Updates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_state_validator_set_updates",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    { "expr": "cometbft_mempool_size", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Mempool Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    { "expr": "cometbft_mempool_size_bytes", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Pending Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_pending_send_bytes",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "{{ value }}" }
   ]
  },
  {
   "title": "Round Voting Power Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_voting_power_percent",
     "legendFormat": "{{ value }}",
     "ref Id": "A"
    }
   ]
  },
  {
   "title": "Consensus Param Updates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "cometbft_state_consensus_param_updates",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "cometbft_p2p_peer_send_bytes_total",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Round Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "cometbft_consensus_round_duration_seconds",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Step Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "cometbft_consensus_step_duration_seconds",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time",
     "legendFormat": "{{ value }}"
    }
   ]
  }
 ]
}