{
 "title": "Validator  Monitoring ( Custom node Exporter)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Validator Uptime Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "story_validator_uptime_percentage",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Validator State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_validator_state", "legendFormat": " " }
   ]
  },
  {
   "title": "Number Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_validator_delegators", "legendFormat": " " }
   ]
  },
  {
   "title": "Validator Missed Last 120 Blocks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_validator_missed_blocks", "legendFormat": " " }
   ]
  },
  {
   "title": "Validator Active Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "story_validator_active_set_rank",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Validator Commission",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_validator_commission", "legendFormat": " " }
   ]
  },
  {
   "title": "Validator Bonded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_validator_total_bonds" }
   ]
  },
  {
   "title": "Network Stake Threshold",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_network_stake_threshold" }
   ]
  },
  {
   "title": "Max Validator Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "story_network_max_set_size" }
   ]
  },
  {
   "title": "Network Lowest Active Set Stake",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "story_network_lowest_active_set_stake"
    }
   ]
  }
 ]
}